notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

sudo: false

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      # this is required to compile keytar
      - libsecret-1-dev
      # this package is essential for testing Electron in a headless fashion
      # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
      - xvfb
      # packages required for electron-installer-debian
      - fakeroot
      - dpkg
      # packages required for electron-installer-redhat
      - rpm
      # packages required for electron-installer-appimage
      - xz-utils
      - xorriso
      - zsync

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "8.11.0"

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache
    - $HOME/.cache/electron-builder

install:
  - node ./vendor/yarn-1.9.2.js install --force

script:
  - |
    node ./vendor/yarn-1.9.2.js lint &&
    node ./vendor/yarn-1.9.2.js validate-changelog &&
    node ./vendor/yarn-1.9.2.js build:prod &&
    node ./vendor/yarn-1.9.2.js test:setup &&
    node ./vendor/yarn-1.9.2.js test

after_failure:
  - node ./vendor/yarn-1.9.2.js test:review
